const BQ4050_COMMANDS = [
  // --- Standard SBS Commands ---
  { hex: "0x01", name: "RemainingCapacityAlarm", type: "SBS", access: "R/W", format: "mAh", desc: "Low capacity alarm threshold" },
  { hex: "0x02", name: "RemainingTimeAlarm", type: "SBS", access: "R/W", format: "min", desc: "Low remaining time-to-fully discharge alarm threshold" },
  { hex: "0x03", name: "BatteryMode", type: "SBS", access: "R/W", format: "Hex", desc: "Various battery operating mode options", bits: { 15: "CAPM", 14: "CHGM", 13: "AM", 9: "PB", 8: "CC", 7: "CF", 1: "PBS", 0: "ICC" }, bitDescs: { 15: "Capacity Mode (0=mAh, 1=10mWh)", 14: "Charging inhibited by host", 13: "Alarm broadcasts (0=enabled, 1=disabled)", 9: "Primary Battery (1=primary, 0=secondary)", 8: "Internal Charge Controller", 7: "Conditioning Cycle requested", 1: "Primary Battery Support", 0: "Internal Charge Control enabled" } },
  { hex: "0x04", name: "AtRate", type: "SBS", access: "R/W", format: "mA", desc: "Value used in calculating AtRateTimeToFull() and AtRateTimeToEmpty()" },
  { hex: "0x05", name: "AtRateTimeToFull", type: "SBS", access: "R", format: "min", desc: "Remaining time-to-fully charge the battery stack" },
  { hex: "0x06", name: "AtRateTimeToEmpty", type: "SBS", access: "R", format: "min", desc: "Remaining time-to-fully discharge the battery stack" },
  { hex: "0x07", name: "AtRateOK", type: "SBS", access: "R", format: "Boolean", desc: "Boolean value that indicates whether the battery can deliver AtRate()" },
  { hex: "0x08", name: "Temperature", type: "SBS", access: "R", format: "0.1°K", desc: "Temperature in units 0.1°K" },
  { hex: "0x09", name: "Voltage", type: "SBS", access: "R", format: "mV", desc: "Sum of the measured cell voltages" },
  { hex: "0x0A", name: "Current", type: "SBS", access: "R", format: "mA", desc: "Measured current from the coulomb counter" },
  { hex: "0x0B", name: "AverageCurrent", type: "SBS", access: "R", format: "mA", desc: "Average current from the coulomb counter" },
  { hex: "0x0C", name: "MaxError", type: "SBS", access: "R", format: "%", desc: "Expected margin of error in the state-of-charge calculation" },
  { hex: "0x0D", name: "RelativeStateOfCharge", type: "SBS", access: "R", format: "%", desc: "Predicted remaining battery capacity as a percentage" },
  { hex: "0x0E", name: "AbsoluteStateOfCharge", type: "SBS", access: "R", format: "%", desc: "Predicted remaining battery capacity as a percentage" },
  { hex: "0x0F", name: "RemainingCapacity", type: "SBS", access: "R", format: "mAh", desc: "Predicted remaining battery capacity" },
  { hex: "0x10", name: "FullChargeCapacity", type: "SBS", access: "R", format: "mAh", desc: "Predicted battery capacity when fully charged" },
  { hex: "0x11", name: "RunTimeToEmpty", type: "SBS", access: "R", format: "min", desc: "Predicted remaining battery capacity based on the present rate of discharge" },
  { hex: "0x12", name: "AverageTimeToEmpty", type: "SBS", access: "R", format: "min", desc: "Predicted remaining battery capacity based on AverageCurrent()" },
  { hex: "0x13", name: "AverageTimeToFull", type: "SBS", access: "R", format: "min", desc: "Predicted time-to-full charge based on AverageCurrent()" },
  { hex: "0x14", name: "ChargingCurrent", type: "SBS", access: "R", format: "mA", desc: "Desired charging current" },
  { hex: "0x15", name: "ChargingVoltage", type: "SBS", access: "R", format: "mV", desc: "Desired charging voltage" },
  { hex: "0x16", name: "BatteryStatus", type: "SBS", access: "R", format: "Hex", desc: "Various battery status information", bits: { 15: "OCA", 14: "TCA", 12: "OTA", 11: "TDA", 9: "RCA", 8: "RTA", 7: "INIT", 6: "DSG", 5: "FC", 4: "FD", 3: "EC3", 2: "EC2", 1: "EC1", 0: "EC0" }, bitDescs: { 15: "Over-Charged Alarm", 14: "Terminate Charge Alarm", 12: "Over-Temperature Alarm", 11: "Terminate Discharge Alarm", 9: "Remaining Capacity Alarm", 8: "Remaining Time Alarm", 7: "Initialization", 6: "Discharging", 5: "Fully Charged", 4: "Fully Discharged", 3: "Error Code bit 3", 2: "Error Code bit 2", 1: "Error Code bit 1", 0: "Error Code bit 0" } },
  { hex: "0x17", name: "CycleCount", type: "SBS", access: "R/W", format: "cycles", desc: "Number of discharge cycles the battery has experienced.", action: "Write" },
  { hex: "0x18", name: "DesignCapacity", type: "SBS", access: "R", format: "mAh", desc: "Theoretical pack capacity" },
  { hex: "0x19", name: "DesignVoltage", type: "SBS", access: "R", format: "mV", desc: "Theoretical pack voltage" },
  { hex: "0x1A", name: "SpecificationInfo", type: "SBS", access: "R", format: "Hex", desc: "Specification Information" },
  { hex: "0x1B", name: "ManufacturerDate", type: "SBS", access: "R", format: "Date", desc: "Pack's manufacturer date" },
  { hex: "0x1C", name: "SerialNumber", type: "SBS", access: "R", format: "Hex", desc: "Assigned pack serial number" },
  { hex: "0x20", name: "ManufacturerName", type: "SBS", access: "R", format: "String", desc: "Pack manufacturer's name" },
  { hex: "0x21", name: "DeviceName", type: "SBS", access: "R", format: "String", desc: "Assigned pack name" },
  { hex: "0x22", name: "DeviceChemistry", type: "SBS", access: "R", format: "String", desc: "Battery chemistry used in the pack" },
  { hex: "0x23", name: "ManufacturerData", type: "SBS", access: "R", format: "Mixed", desc: "ManufacturerInfo by default" },
  { hex: "0x2F", name: "Authenticate", type: "SBS", access: "R/W", format: "Hex", desc: "SHA-1 authentication" },
  { hex: "0x3C", name: "CellVoltage4", type: "SBS", access: "R", format: "mV", desc: "Cell 4 voltage." },
  { hex: "0x3D", name: "CellVoltage3", type: "SBS", access: "R", format: "mV", desc: "Cell 3 voltage." },
  { hex: "0x3E", name: "CellVoltage2", type: "SBS", access: "R", format: "mV", desc: "Cell 2 voltage." },
  { hex: "0x3F", name: "CellVoltage1", type: "SBS", access: "R", format: "mV", desc: "Cell 1 voltage." },
  { hex: "0x4A", name: "BTPDischargeSet", type: "SBS", access: "R/W", format: "mAh", desc: "Updates the BTP set threshold for discharge mode" },
  { hex: "0x4B", name: "BTPChargeSet", type: "SBS", access: "R/W", format: "mAh", desc: "Updates the BTP set threshold for charge mode" },
  { hex: "0x4F", name: "StateOfHealth", type: "SBS", access: "R", format: "%", desc: "State-of-health (SoH) information of the battery in percentage" },

  // --- MAC Commands ---
  { hex: "0x0001", name: "DeviceType", type: "MAC", access: "R", format: "Hex", desc: "IC part number" },
  { hex: "0x0002", name: "FirmwareVersion", type: "MAC", access: "R", format: "Hex", desc: "Firmware revision" },
  { hex: "0x0010", name: "ShutdownMode", type: "MAC", access: "W", format: "Hex", desc: "Send to SHUTDOWN mode before shipping", action: "Send" },
  { hex: "0x0011", name: "SleepMode", type: "MAC", access: "W", format: "Hex", desc: "Send to SLEEP mode. Requires 2x if SEALED", action: "Send 2x (SEALED)", seq: 2, delay: 0 },
  { hex: "0x001D", name: "FuseToggle", type: "MAC", access: "W", format: "Hex", desc: "Manually activates/deactivates the FUSE output", action: "Toggle" },
  { hex: "0x001E", name: "PrechargeFET", type: "MAC", access: "W", format: "Hex", desc: "Turns on/off PCHG FET", action: "Toggle" },
  { hex: "0x001F", name: "ChargeFET", type: "MAC", access: "W", format: "Hex", desc: "Turns on/off CHG FET", action: "Toggle" },
  { hex: "0x0020", name: "DischargeFET", type: "MAC", access: "W", format: "Hex", desc: "Turns on/off DSG FET", action: "Toggle" },
  { hex: "0x0022", name: "FETControl", type: "MAC", access: "W", format: "Hex", desc: "Disables/enables FW control of FETs", action: "Toggle" },
  { hex: "0x0028", name: "LifetimeDataReset", type: "MAC", access: "W", format: "Hex", desc: "Resets Lifetime Data in flash", action: "Send" },
  { hex: "0x0030", name: "SealDevice", type: "MAC", access: "W", format: "Hex", desc: "Seals the device, disabling access", action: "Send" },
  
  { hex: "0x0414,0x3672", name: "UnsealDevice (TI Default)", type: "MAC", access: "W", format: "Hex", desc: "Unseals the device (Default TI keys)", action: "Send Sequence", seq: 2, delay: 10 },
  
  { hex: "0x0050", name: "SafetyAlert", type: "MAC", access: "R", format: "Hex", desc: "Safety Alert flags", bits: { 27: "UTD", 26: "UTC", 25: "PCHGC", 24: "CHGV", 23: "CHGC", 22: "OC", 21: "CTOS", 20: "CTO", 19: "PTOS", 18: "PTO", 16: "OTF", 14: "CUVC", 13: "OTD", 12: "OTC", 11: "ASCDL", 10: "ASCD", 9: "ASCCL", 8: "ASCC", 7: "AOLDL", 6: "AOLD", 5: "OCD2", 4: "OCD1", 3: "OCC2", 2: "OCC1", 1: "COV", 0: "CUV" } },
  { hex: "0x0051", name: "SafetyStatus", type: "MAC", access: "R", format: "Hex", desc: "Safety Status flags", bits: { 27: "UTD", 26: "UTC", 25: "PCHGC", 24: "CHGV", 23: "CHGC", 22: "OC", 21: "CTOS", 20: "CTO", 19: "PTOS", 18: "PTO", 16: "OTF", 14: "CUVC", 13: "OTD", 12: "OTC", 11: "ASCDL", 10: "ASCD", 9: "ASCCL", 8: "ASCC", 7: "AOLDL", 6: "AOLD", 5: "OCD2", 4: "OCD1", 3: "OCC2", 2: "OCC1", 1: "COV", 0: "CUV" } },
  { hex: "0x0054", name: "OperationStatus", type: "MAC", access: "R", format: "Hex", desc: "Operation Status flags", bits: { 29: "EMSHUT", 28: "CB", 27: "SLPCC", 26: "SLPAD", 25: "SMBLCAL", 24: "INIT", 23: "SLEEPM", 22: "XL", 21: "CAL_OFFSET", 20: "CAL", 19: "AUTOCALM", 18: "AUTH", 17: "LED", 16: "SDM", 15: "SLEEP", 14: "XCHG", 13: "XDSG", 12: "PF", 11: "SS", 10: "SDV", 9: "SEC1", 8: "SEC0", 7: "BTP_INT" } },
  { hex: "0x0055", name: "ChargingStatus", type: "MAC", access: "R", format: "Hex", desc: "Charging Status flags", bits: { 15: "TAPER", 10: "CCC", 9: "CVR", 8: "CCR", 7: "VCT", 6: "MCHG", 5: "SU", 4: "IN", 3: "HV", 2: "MV", 1: "LV", 0: "PV" } },
  { hex: "0x0056", name: "GaugingStatus", type: "MAC", access: "R", format: "Hex", desc: "Gauging Status flags", bits: { 15: "VDQ", 14: "EDV2", 13: "EDV1", 10: "FCCX", 7: "CF", 6: "DSG", 5: "EDV0", 4: "BAL_EN", 3: "TC", 2: "TD", 1: "FC", 0: "FD" } },
  { hex: "0x0071", name: "DAStatus1", type: "MAC", access: "R", format: "Mixed", desc: "Cell Voltages, Pack Voltage, Bat Voltage, Cell Currents, Cell Powers, Power" },
  { hex: "0x0072", name: "DAStatus2", type: "MAC", access: "R", format: "Mixed", desc: "Internal temp, TS1, TS2, TS3, TS4, Cell Temp, FETTemp" }
];
